"""new relation

Revision ID: 495ccb3af08f
Revises: 8c2f35238a14
Create Date: 2025-09-01 21:38:12.034719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495ccb3af08f'
down_revision: Union[str, Sequence[str], None] = '8c2f35238a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_group_association',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('account_id', 'group_id')
    )
    op.drop_constraint(op.f('group_group_id_key'), 'group', type_='unique')
    op.drop_constraint(op.f('group_account_id_fkey'), 'group', type_='foreignkey')
    op.drop_column('group', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('group_account_id_fkey'), 'group', 'account', ['account_id'], ['id'])
    op.create_unique_constraint(op.f('group_group_id_key'), 'group', ['group_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('account_group_association')
    # ### end Alembic commands ###
