"""fix

Revision ID: 6c0ed5026fd7
Revises: 495ccb3af08f
Create Date: 2025-09-02 00:27:46.289087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0ed5026fd7'
down_revision: Union[str, Sequence[str], None] = '495ccb3af08f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_group_association')
    op.add_column('group', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_group_account', 'group', ['group_id', 'account_id'])
    op.create_foreign_key(None, 'group', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_constraint('uq_group_account', 'group', type_='unique')
    op.drop_column('group', 'account_id')
    op.create_table('account_group_association',
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('account_group_association_account_id_fkey')),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('account_group_association_group_id_fkey')),
    sa.PrimaryKeyConstraint('account_id', 'group_id', name=op.f('account_group_association_pkey'))
    )
    # ### end Alembic commands ###
