"""more model

Revision ID: 8c2f35238a14
Revises: db4704b8dd3b
Create Date: 2025-09-01 20:26:07.655334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2f35238a14'
down_revision: Union[str, Sequence[str], None] = 'db4704b8dd3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_ip_port_username', 'proxy', ['ip', 'port', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ip_port_username', 'proxy', type_='unique')
    # ### end Alembic commands ###
