"""empty message

Revision ID: 9c6e3a801841
Revises: 4a0f02c0e042
Create Date: 2025-09-03 17:21:01.247853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6e3a801841'
down_revision: Union[str, Sequence[str], None] = '4a0f02c0e042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'comment', ['comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='unique')
    op.drop_column('comment', 'comment_id')
    # ### end Alembic commands ###
