"""empty message

Revision ID: e175e2d66714
Revises: 66fc7fa213f9
Create Date: 2025-09-03 13:49:47.715639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e175e2d66714'
down_revision: Union[str, Sequence[str], None] = '66fc7fa213f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_analyzed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_analyzed')
    # ### end Alembic commands ###
